format = """
$directory\
$git_branch\
$git_status\
$fill\
$python\
$lua\
$nodejs\
$golang\
$haskell\
$rust\
$dotnet\
$package\
$aws\
$azure\
$docker_context\
$jobs\
$cmd_duration\
$line_break\
$character"""

add_newline = true
palette = 'nord'

[directory]
style = 'bold fg:dark_blue'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false

[directory.substitutions]
'Documents' = '󰈙'
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '

[git_branch]
style = 'fg:green'
symbol = ' '
format = '[on](white) [$symbol$branch ]($style)'

[git_status]
style = 'fg:green'
format = '([$all_status$ahead_behind]($style) )'

[fill]
symbol = ' '

[python]
style = 'teal'
symbol = ' '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = true
pyenv_prefix = ''

[lua]
symbol = ' '

[nodejs]
style = 'blue'
symbol = ' '

[golang]
style = 'blue'
symbol = ' '

[haskell]
style = 'blue'
symbol = ' '

[rust]
style = 'orange'
symbol = ' '

[dotnet]
symbol = ' '
style = 'blue'
format = 'via [$symbol($version )]($style)'

[package]
symbol = '󰏗 '

[aws]
symbol = ' '
style = 'yellow'
format = 'on [$symbol($profile )(\($region\) )]($style)'
disabled = true
[aws.region_aliases]
us-west-2 = 'W2'
us-east-1 = 'E1'
[aws.profile_aliases]
actual-profile-name = 'my-alias'

[azure]
disabled = false
format = 'on [$symbol($subscription)]($style) '
symbol = '󰠅 '
style = 'blue bold'
[azure.subscription_aliases]
actual-subscription-name = 'my-alias'

[docker_context]
symbol = ' '
style = 'fg:#06969A'
format = '[$symbol]($style) $path'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

[jobs]
symbol = ' '
style = 'red'
number_threshold = 1
format = '[$symbol]($style)'

[cmd_duration]
min_time = 500
style = 'fg:gray'
format = '[$duration]($style)'

[palettes.nord]
dark_blue = '#5E81AC'
blue = '#81A1C1'
teal = '#88C0D0'
red = '#BF616A'
orange = '#D08770'
green = '#A3BE8C'
yellow = '#EBCB8B'
purple = '#B48EAD'
gray = '#434C5E'
black = '#2E3440'
white='#D8DEE9'

[palettes.kanagawa]
fujiWhite = "#DCD7BA"
oldWhite = "#C8C093"
sumiInk0 = "#16161D"
sumiInk1 = "#1F1F28"
sumiInk2 = "#2A2A37"
sumiInk3 = "#363646"
sumiInk4 = "#54546D"
fujiGray = "#727169"
katanaGray = "#717C7C"
waveBlue1 = "#223249"
waveBlue2 = "#2D4F67"
winterBlue = "#252535"
dragonBlue = "#658594"
crystalBlue = "#7E9CD8"
springBlue = "#7FB4CA"
lightBlue = "#A3D4D5"
waveAqua1 = "#6A9589"
waveAqua2 = "#7AA89F"
springGreen = "#98BB6C"
autumnGreen = "#76946A"
winterGreen = "#2B3328"
autumnYellow = "#DCA561"
winterYellow = "#49443C"
boatYellow1 = "#938056"
boatYellow2 = "#C0A36E"
carpYellow = "#E6C384"
roninYellow = "#FF9E3B"
surimiOrange = "#FFA066"
autumnRed = "#C34043"
winterRed = "#43242B"
samuraiRed = "#E82424"
waveRed = "#E46876"
peachRed = "#FF5D62"
springViolet1 = "#938AA9"
springViolet2 = "#9CABCA"
oniViolet = "#957FB8"
sakuraPink = "#D27E99"


